# fly.toml app configuration file generated for echobackend on 2024-11-25T09:50:39+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echobackend'
primary_region = 'sin'

[build]
  image = 'cecep31/echobackend:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
